# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClinicsAndDoctors' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClinicsAndDoctors
pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage', '~> 3.2'
pod 'SwiftyJSON'
pod 'PKHUD'
pod 'PromiseKit'
pod 'ARSLineProgress'
pod 'SwiftMessages'
#pod 'ObjectMapper', '~> 2.2'
#pod 'AlamofireObjectMapper', '~> 4.0'
pod 'Argo'
pod 'AELog'
#pod 'IHKeyboardAvoiding'
pod 'SideMenu'
pod 'TPKeyboardAvoiding'
pod 'GoogleMaps'
end
