# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClinicsAndDoctors' do

#pod 'Google-Maps-iOS-Utils'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClinicsAndDoctors

pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage', '~> 3.2'
pod 'SwiftyJSON'
pod 'PKHUD'
pod 'PromiseKit'
pod 'PromiseKit/Alamofire', '~> 4.0'
pod 'Cosmos', '~> 12.0'
pod 'ARSLineProgress'
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'AELog'
pod 'SideMenu'
pod 'TPKeyboardAvoiding'
pod 'GoogleMaps'
pod 'NVActivityIndicatorView'
pod 'YYWebImage'
pod 'ClusterKit'
end
